### ISSUE TITLE
I do not always receive the update from OnUserOrdersUpdate and OnUserExecutionsUpdate 

### ISSUE THREAD

**Issue by wil70** [ridicoulous/Bitmex.Net#11]
Thanks for this great project
Streaming trades+quotes + sending order, cancel etc.. all work great

The thing that work sometime but not always and I can not figure out why are			
             _sockeStream.OnUserOrdersUpdate += SocketClient_OnUserOrdersUpdate;
             _sockeStream.OnUserExecutionsUpdate += SocketClient_OnUserExecutionsUpdate;
             _sockeStream.OnUserPositionsUpdate += _sockeStream_OnUserPositionsUpdate;
(I send an order and the update data come but sometime it stops sending those updates or I do not get any update from the beginning. The trades and quptes seems to be always coming. Even without those updates the order are sent and being processed by bitmex as I can see them on the ui...)

Work all the time:
             _sockeStream.OnTradeUpdate += OnTrade;
             _sockeStream.OnQuotesUpdate += OnQuote;

Not sure it works:
             _sockeStream.OnUserTransactionsUpdate += _sockeStream_OnUserTransactionsUpdate;

**Comment by ridicoulous** [comment]
Hello. 

First of all you should turn on Autoreconnect at client. 

Does you have some logs? 
You can turn on debug logs at client by setting up client's config LogVerbosity and LogWriters

Can not say any about transactions updates, I didn't use it, may be this is only daily pushes about realized PNL?

Can you show your client initialization?

**Comment by wil70** [comment]
From March 22, I just move to another exchange!Thanks!


    On Monday, September 20, 2021, 02:12:21 PM PDT, Artem Kurianov ***@***.***> wrote:  
 
 


Closed #11.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
