### ISSUE TITLE
Limit order not returning the right avg price and price that is being filled

### ISSUE THREAD

**Issue by wil70** [ridicoulous/Bitmex.Net#12]
Hello

When I use limit orders, and let say the price is at $100 on the ask with a qty of 1 and $101 with qty of 2
If I send a buy limit order of $101 with qty of 5, it should fill  1 @ $100 and 2 at $101 and it should send the events with the right math, what it returns is not correct at all.
 The last price, avg price, price etc...are ok for market order but not for limit order.

**Comment by ridicoulous** [comment]
Hello. 

I assume Bitmex returns price that was setted at order placing. 

Do you have some logs?
Or provide more details about fields with wrong values

**Comment by wil70** [comment]
From March 22, I just move to another exchange!Thanks!
    On Monday, September 20, 2021, 02:12:12 PM PDT, Artem Kurianov ***@***.***> wrote:  
 
 


Closed #12.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
