### ISSUE TITLE
CryptoNet upgrade

### ISSUE THREAD

**Issue by jrocha** [ridicoulous/Bitmex.NET#15]
CryptoExchange.Net has changed substantially in the last few versions. 

I'm trying to get Bitmex.Net compiled againt this new version. Since it is not going to be a small patch I would like to hear from you guys the best way we can handle this effort.

**Comment by ridicoulous** [comment]
ok, I'll take a look

**Comment by ridicoulous** [comment]
@jrocha  feel free reopen if you'll have any issues
