### ISSUE TITLE
GetUserWalletHistory error

### ISSUE THREAD

**Issue by lploumen** [ridicoulous/Bitmex.NET#21]
Hi,
When trying to get user wallet history, I got this error :

> [1] Deserialize JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path '[0].transactTime', line 1, position 227. data: [
  {
    "transactID": "00000000-0000-0000-0000-000000000000",
    "account": 1280812,
    "currency": "XBt",
    "transactType": "UnrealisedPNL",
    "amount": -69252,
    "fee": 0,
    "transactStatus": "Pending",
    "address": "ETHUSD",
    "tx": "",
    "text": "",
    "transactTime": null,
    "walletBalance": 434108091,
    "marginBalance": 434038839,
    "timestamp": null
  },

It seems that transactTime property can be null...
Any chance it gets fixed ?

Best regards,

**Comment by ridicoulous** [comment]
Shure, I’ll fix it tomorrow

**Comment by ridicoulous** [comment]
@lploumen hi. try update to 1.53 version.
