### ISSUE TITLE
Bitmex CryptoExchange.Net Update

### ISSUE THREAD

**Issue by MatriksIQ** [ridicoulous/Bitmex.NET#30]
We use binance.net library. We had to update the version of this library. We also use bitmex.net. When we update binance.net, the versions of CryptoExchange.Net library of these libraries have conflict. Can you update CryptoExchange.Net of bitmex.net?

Thanks,

**Comment by alokym86** [comment]
@MatriksIQ Because of russia invasion, @ridicoulous has no time to support this repo. You can make your own update and send a pull request, or wait while someone else does it.
