### ISSUE TITLE
Trouble reconnecting after connection loss

### ISSUE THREAD

**Issue by vahdetunal** [ridicoulous/Bitmex.Net#5]
Hello,

I have been testing the library in order to integrate it into an application. I have encountered some issues which I will describe below. It works really well overall, thank you for the great library!

I am creating two socket clients. The first client is created without authorization and is used for orderbook subscription. The second client is created with login info and subscribes to position, margin, order and execution streams. I have been doing my tests on a testnet account.

The orderbook client works perfectly. Can reconnect if the internet connection has interruptions and never drops off otherwise. However, I have encountered some problems with the authorized client.

- The authorized client cannot cannot reconnect after the internet connection is interrupted.

```
2020.11.06 19:48:11:068 | Warning | No data received for 00:00:20, reconnecting socket
2020.11.06 19:48:11:073 | Debug | Socket 3 closing
2020.11.06 19:48:13:077 | Debug | Socket 3 closed
2020.11.06 19:48:16:089 | Info | Socket 3 Connection lost, will try to reconnect after 00:00:05
2020.11.06 19:48:21:108 | Debug | Socket 3 resetting
2020.11.06 19:48:21:113 | Debug | Socket 3 connecting
2020.11.06 19:48:21:118 | Debug | Socket catched exception System.Net.Sockets.SocketException (0x80004005): No such host is known
2020.11.06 19:48:21:122 | Debug | Socket 3 connection failed, state: Closed
2020.11.06 19:48:21:126 | Debug | Socket 3 failed to reconnect
2020.11.06 19:48:26:145 | Debug | Socket 3 resetting
2020.11.06 19:48:26:149 | Debug | Socket 3 connecting
2020.11.06 19:48:26:154 | Debug | Socket catched exception System.Net.Sockets.SocketException (0x80004005): No such host is known
2020.11.06 19:48:26:158 | Debug | Socket 3 connection failed, state: Closed
2020.11.06 19:48:26:163 | Debug | Socket 3 failed to reconnect
2020.11.06 19:48:31:176 | Debug | Socket 3 resetting
2020.11.06 19:48:31:181 | Debug | Socket 3 connecting
2020.11.06 19:48:31:186 | Debug | Socket catched exception System.Net.Sockets.SocketException (0x80004005): No such host is known
2020.11.06 19:48:31:190 | Debug | Socket 3 connection failed, state: Closed
2020.11.06 19:48:31:194 | Debug | Socket 3 failed to reconnect
2020.11.06 19:48:36:208 | Debug | Socket 3 resetting
2020.11.06 19:48:36:214 | Debug | Socket 3 connecting
2020.11.06 19:48:36:663 | Debug | Socket catched exception System.Exception: unknown server protocol version
2020.11.06 19:48:36:669 | Debug | Socket 3 connection failed, state: Connecting
2020.11.06 19:48:36:673 | Debug | Socket 3 failed to reconnect
2020.11.06 19:48:41:693 | Debug | Socket 3 resetting
2020.11.06 19:48:41:697 | Debug | Socket 3 connecting
2020.11.06 19:48:42:069 | Debug | Socket catched exception System.Exception: unknown server protocol version
2020.11.06 19:48:42:074 | Debug | Socket 3 connection failed, state: Connecting
2020.11.06 19:48:42:078 | Debug | Socket 3 failed to reconnect
```

- I am using SendPeriodic to keep the authorized client alive by sending ping messages. The pong response from the server encounters an error and does not trigger OnPongReceived.

```
2020.11.06 19:47:28:007 | Debug | Sending periodic
2020.11.06 19:47:28:011 | Debug | Socket 3 sending data: ping
2020.11.06 19:47:28:170 | Debug | Socket 3 received data: pong
2020.11.06 19:47:28:175 | Error | Deserialize JsonReaderException: Unexpected character encountered while parsing value: p. Path '', line 0, position 0., Path: , LineNumber: 0, LinePosition: 0. Data: pong
2020.11.06 19:47:28:179 | Debug | Message not handled: pong
```

**Comment by ridicoulous** [comment]
Hello, @vahdetunal unfortunally it is a known issue, and I can not figure out yet with it, cause some times it do reconnect without troubles. For private endpoints in my application I solve this problem by tuning off auto reconnecting and handling OnSocketClose event. At handler my private endpoints client is disposed and created and subscribed again. Stay tuned
And one question, could you please describe your environement that runs your app?

**Comment by vahdetunal** [comment]
It is a WPF desktop application built for Net 4.7.2. Since Net 4.7.2 does not support netstandard 2.1, I have removed [NotNull] attributes and compiled the library for netstandard 2.0. The application is intended for windows 7 or later. The machine I have been using for tests is running Windows 10 pro.

In case any further hardware/driver info could be helpful, there is a Dxdiag report attached as well.
[DxDiag.txt](https://github.com/ridicoulous/Bitmex.Net/files/5520024/DxDiag.txt)

**Comment by ridicoulous** [comment]
@vahdetunal can you try to reproduce with new pre-release package version 1.4.0-pre?

**Comment by vahdetunal** [comment]
My private endpoints client is reconnecting without any problem with the pre-release version. The issue seems to be solved, thank you.

**Comment by miqteam** [comment]
I have the same problem with version 1.4.0

**Comment by ridicoulous** [comment]
> I have the same problem with version 1.4.0

Can you provide more detais, cause after two weeks uptime my application got several reconnects and all of them was successful

**Comment by miqteam** [comment]
After i updated cryptoexchange library it was able to reconnect. I will watch it. 
Thanks
