### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by miqteam** [ridicoulous/Bitmex.Net#8]
If my ip has been blocked, i get json deserialize error.
Here is the message:
<code>
&lt;html&gt;
&lt;head&gt;&lt;title&gt;403 Forbidden&lt;/title>&lt;/head&gt;
&lt;body&gt;
&lt;center&gt;&lt;h1&gt;403 Forbidden&lt;/h1&gt;&lt;/center&gt;
&lt;/body&gt;
&lt;/html&gt;
</code>

Can you handle this?

**Comment by ridicoulous** [comment]
You can try to reproduce with new pre-release package version 1.4.1-pre. I see some updates at base library and think this problem would be solved. 

Also, to prevent rate limiting bans, you have to set limiters at client instatiating according [to rate limit docs](https://www.bitmex.com/app/restAPI#---2) like this:

```cs
var client = new BitmexClient(new BitmexClientOptions()
{
    ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(configuration["testnet:key"], configuration["testnet:secret"]),
    RateLimiters = new List<CryptoExchange.Net.Interfaces.IRateLimiter>() { new RateLimiterTotal(10, TimeSpan.FromSeconds(1)), new RateLimiterTotal(60, TimeSpan.FromMinutes(1))},
    RateLimitingBehaviour = CryptoExchange.Net.Objects.RateLimitingBehaviour.Fail
});
```

**Comment by miqteam** [comment]
Thanks i will try
